version: '3'

services:

  redis:
    image: redis:6.0-rc2-buster
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123.
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: Laravel123.
    ports:
      - "3306:3306"

  php:
    build:
      context: ./docker/php
      args:
        - LARAVEL_ROOT=/opt/project
    restart: always
    ports:
      - "9000:9000"
    environment:
      - XDEBUG_CONFIG="idekey=${XDEBUG_IDE_KEY} remote_enable=1 remote_port=${XDEBUG_REMOTE_PORT} remote_host=172.17.0.1 remote_connect_back=0"
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ./${CODE_DIR}:${LARAVEL_ROOT}

  nginx:
    build:
      context: ./docker/nginx
      args:
        - USER=www-data
        - GROUP=www-data
        - LARAVEL_ROOT=${LARAVEL_ROOT}
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./${CODE_DIR}:${LARAVEL_ROOT}
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
        #command: /bin/bash -c "envsubst < ./templates/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - php:php

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # web interface
      - "1025:1025"  # SMTP port: set $CFG->smtphosts='mailcatcher:1025';

volumes:
  mysql_data:
